language: go

go: 
    - 1.6.2

before_install:
    - sudo pip install --user codecov
    - go get -v github.com/Masterminds/glide
    - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 21ff6d397ccca910873d8eaabab6a941c364cc70 && go install && cd -

install:
    - glide install

script:
     - go test -coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
