language: go

go: 
    - 1.6.2

before_install:
    - sudo pip install --user codecov

install:
    - glide install

script:
     - go test -coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
